name: github-pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: github-pages
    runs-on: ubuntu-latest
    container: zalgo3/texlive
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build PDF file
        run: latexmk resume.tex && latexmk -c && mkdir -p pdf && cp resume.pdf ./pdf/
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pdf
